Repository onied/main, pull requests merged in 2025-05, with the labels that each got.

#179 Дизайн поиска курсов
  mobile/design_courses/.gitignore
  mobile/design_courses/.metadata
  mobile/design_courses/README.md
  mobile/design_courses/analysis_options.yaml
  mobile/design_courses/android/.gitignore
  mobile/design_courses/android/app/build.gradle.kts
  mobile/design_courses/android/app/src/main/AndroidManifest.xml
  mobile/design_courses/android/app/src/main/kotlin/com/example/design_courses/MainActivity.kt
  mobile/design_courses/android/app/src/main/res/drawable-v21/launch_background.xml
  mobile/design_courses/android/app/src/main/res/drawable/launch_background.xml
  mobile/design_courses/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  mobile/design_courses/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  mobile/design_courses/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  mobile/design_courses/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  mobile/design_courses/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  mobile/design_courses/android/app/src/main/res/values-night/styles.xml
  mobile/design_courses/android/app/src/main/res/values/styles.xml
  mobile/design_courses/android/app/src/profile/AndroidManifest.xml
  mobile/design_courses/android/build.gradle.kts
  mobile/design_courses/android/gradle.properties
  mobile/design_courses/android/gradle/wrapper/gradle-wrapper.properties
  mobile/design_courses/android/settings.gradle.kts
  mobile/design_courses/lib/app/app.dart
  mobile/design_courses/lib/app/app_theme.dart
  mobile/design_courses/lib/data/course_card_dto.dart
  mobile/design_courses/lib/data/course_preview_dto.dart
  mobile/design_courses/lib/data/repository_mock.dart
  mobile/design_courses/lib/main.dart
  mobile/design_courses/lib/pages/course_preview_page.dart
  mobile/design_courses/lib/pages/home_page.dart
  mobile/design_courses/lib/pages/search_results_page.dart
  mobile/design_courses/lib/widgets/catalog/search_filters.dart
  mobile/design_courses/lib/widgets/catalog/search_mode_app_bar.dart
  mobile/design_courses/lib/widgets/course_preview/allow_certificates.dart
  mobile/design_courses/lib/widgets/course_preview/author_block.dart
  mobile/design_courses/lib/widgets/course_preview/course_program.dart
  mobile/design_courses/lib/widgets/shared/app_bar.dart
  mobile/design_courses/lib/widgets/shared/button.dart
  mobile/design_courses/lib/widgets/shared/course_card.dart
  mobile/design_courses/lib/widgets/shared/picture_preview.dart
  mobile/design_courses/pubspec.lock
  mobile/design_courses/pubspec.yaml
  mobile/design_courses/test/widget_test.dart
  mobile/design_courses/web/favicon.png
  mobile/design_courses/web/icons/Icon-192.png
  mobile/design_courses/web/icons/Icon-512.png
  mobile/design_courses/web/icons/Icon-maskable-192.png
  mobile/design_courses/web/icons/Icon-maskable-512.png
  mobile/design_courses/web/index.html
  mobile/design_courses/web/manifest.json
Labels: Application

#187 Создать сервис на бэкенде
  backend/Onied/GraphqlService/Dtos/Block/Response/SummaryBlockResponse.cs
  backend/Onied/GraphqlService/Dtos/Block/Response/TaskResponse.cs
  backend/Onied/GraphqlService/Dtos/Block/Response/TasksBlockResponse.cs
  backend/Onied/GraphqlService/Dtos/Block/Response/VariantResponse.cs
  backend/Onied/GraphqlService/Dtos/Block/Response/VideoBlockResponse.cs
  backend/Onied/GraphqlService/Dtos/Course/Response/CourseResponse.cs
  backend/Onied/GraphqlService/Extensions/ServiceCollectionExtensions.cs
  backend/Onied/GraphqlService/GraphqlService.csproj
  backend/Onied/GraphqlService/Profiles/AppMappingProfile.cs
  backend/Onied/GraphqlService/Program.cs
  backend/Onied/GraphqlService/Properties/launchSettings.json
  backend/Onied/GraphqlService/Quiries/CourseQuery.cs
  backend/Onied/GraphqlService/appsettings.json
  backend/Onied/Onied.sln
  backend/Onied/Users/Users/ocelot.json
Labels: Backend

#189 Добавил логику авторизации
  mobile/onied/android/app/src/main/AndroidManifest.xml
  mobile/onied/lib/app/app.dart
  mobile/onied/lib/app/config.dart
  mobile/onied/lib/app/injection.dart
  mobile/onied/lib/blocs/authorization/authorization_bloc.dart
  mobile/onied/lib/blocs/authorization/authorization_bloc_event.dart
  mobile/onied/lib/blocs/authorization/authorization_bloc_state.dart
  mobile/onied/lib/blocs/profile_info/profile_info_bloc.dart
  mobile/onied/lib/blocs/profile_info/profile_info_bloc_state.dart
  mobile/onied/lib/main.dart
  mobile/onied/lib/models/auth/authorization_data.dart
  mobile/onied/lib/models/auth/credentials.dart
  mobile/onied/lib/models/enums/auth_status.dart
  mobile/onied/lib/models/user_model.dart
  mobile/onied/lib/pages/authorization/authorization_page.dart
  mobile/onied/lib/pages/authorization/components/forms/login_form.dart
  mobile/onied/lib/pages/authorization/components/forms/registration_form.dart
  mobile/onied/lib/pages/authorization/registration_page.dart
  mobile/onied/lib/pages/profile_info/profile_info.dart
  mobile/onied/lib/providers/authorization_api.dart
  mobile/onied/lib/providers/authorization_provider.dart
  mobile/onied/lib/providers/user_provider.dart
  mobile/onied/lib/providers/vk_auth_provider.dart
  mobile/onied/lib/repositories/user_repository.dart
  mobile/onied/lib/requests/forms/login_form_data.dart
  mobile/onied/lib/requests/forms/login_vk_form_data.dart
  mobile/onied/lib/requests/forms/registration_form_data.dart
  mobile/onied/lib/requests/profile_changed_request.dart
  mobile/onied/lib/requests/refresh_request.dart
  mobile/onied/pubspec.lock
  mobile/onied/pubspec.yaml
Labels: Application

#192 Починил превьюшки для SVG файлов
  mobile/onied/lib/components/picture_preview/picture_preview.dart
  mobile/onied/lib/pages/home/home_page.dart
Labels: bug, Application
